dist: xenial
language: python
python: 3.6
branches:
  only:
  - master
  - dev
install:
- pip install nbconvert requests jinja2 mkdocs mkdocs-material pygments pymdown-extensions
  mkdocs-exclude
- pip install mknotebooks
script: true
before_deploy:
- mkdocs build --verbose --clean
deploy:
- provider: pypi
    username: __token__
    server: https://test.pypi.org/legacy/
    on:
      branch: dev
    password:
      secure: lfdlhjA11y6VEvlSx2NnxXV2JQjKCkHcM51VBARgrGBkMouY2arXTEyWZwVXNYa7caC6ekk/BdcIooINtcLzQpHlfPq2tI5cwzVspGlRAInhL+4AdNl20YBoOS3BhLQPWCd+jcqNkCrvErI1FNDQI4DB18Na+21CJpNXuj22RH1QaABDiZuYC4mKU4oOg1VuT+Nse5m0qSQ7WJiWskVA5qumb9BL76DgFgW37n9SuOctdevHYx4ebgSP7Tvz81XUZx89B6qCwFJu6Bzi+tMOpKjx1jAaRvjW0ttMX5/hSXgFKEUz6fzPuxkAZgj6mfV3SCQM1q2zImT9geC8eap/SEUkG8q4jYRqjBlspIr7eIQWpNMlQDZchQSBYs0bRUODiF31HrCwXVFWK1xHwbzB5rXt4R9bv4uvhkWIvVH+ACcC5GYAxJslInROY6M99Tt8HpMGsrBGmU1bT+RRYWadsyA4pmg/BgCaK3Fw2Y8mIEhBxsohsgTwdZfDn4RGOp+8FzshQe/j5r1LNFJUD5G+YWvbplV5ySPE3if+/4nLA3LDrDB931Ys0duvkUqe3IeioneiB+2DOUHhjmEDY9dOd+dju0dDeF0PL4TcJrlXxOo8oVRq3CZz/Q08ubHj3JaqDatP6UmTm04kEes8uenl8vwggGjUb3gZEgZWSqVS/Jk=
  - provider: pypi
    username: __token__
    on:
      branch: main
    password:
      secure: BQq5jbwy70rRR9jngGFSvPhBH2sVB/ntUxQ2TYD0Khcl0C+UOU/NCDYpxW9cB/ZoMnVWGeiKgDVOQrRFmcQk8JT49xctk9awaCxczKgJ5SfOv9lwIIpdZQ+d7QPDgI9P0lhoTfaIFZx00rRKtYr07g0mzGOBKDOdMn/22dOjp7CRfIPVfDOPQc5mySI6R9hHqYGaCIMmpzFhV5Q2+lxpYqK8f9usO5jkySXdP5boRrd+RYCEaP47IuIsr7zNXEkhWQSbDx35gV7JKe5g2HfZUBu9SI8GFbD02ncnpLRUQFLd7aUIx7oxnIhVUd/S6tlYKNfQyWuzAcEcRqxTMZMUj8AGlA7P1BpYJvU2FsLtX5Pf1jJwWTht07I9UpOMEhccJHvB1oDcmICKUB8wQFEKBYAWd3CbBGIXv7L5e/iTGG3J9cpmoN2XqzhUd3JBGBnKzy92cdSX/2vdw6XjL8NB1T5EVCsc/1vRrjIfALwEDxzX78Jo0oz9sq8AyHeTZWCTFI/q186FfSO8BXEuGY5AdhgWYbwB1mWW/QICgWgv+2S1swBorgVJ790eBleLIQk93PtwITom3Fv4x7tHWZwF1mfuwawEGdWEuo/vdM4T24wvU69DeT9rUs7sNbirWeOCaHVyakb3GEIqwhZEU+PxkIUMC0rt14tEynff5hiXsdU=


