{% set version = "2.2.2" %}
{% set name = "pycoMeth" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "
  entry_points:
    - pycoMeth=pycoMeth.__main__:main
    - pycometh=pycoMeth.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=3.7
    - pip>=19.2.1
    - ripgrep>=11.0.1
    - cython
  run:
    - numpy==1.22.2
    - scipy==1.4.1
    - statsmodels==0.13.2
    - pandas==1.4.1
    - Jinja2==3.0.3
    - plotly==5.6.0
    - pyfaidx==0.6.4
    - tqdm==4.62.3
    - colorlog==6.6.0
    - nbformat==5.1.3
    - meth5>=1.1.1

test:
  imports:
    - pycoMeth.FileParser
    - pycoMeth.CoordGen
    - pycoMeth.Meth_Comp
    - pycoMeth.Meth_Seg
    - pycoMeth.Comp_Report
  commands:
    - pycoMeth Meth_Comp --help
    - pycoMeth Meth_Seg --help
    - pycoMeth Comp_Report --help
    - pycoMeth CGI_Finder --help

about:
  home: "https://github.com/snajder-r/pycoMeth,"
  license: "MIT"
  summary: "DNA methylation analysis for Oxford Nanopore DNA sequencing datasets downstream to Nanopolish"
