{% set version = "2.0.0" %}
{% set name = "pycoMeth" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "pip install {{ name }}-{{ version }}.tar.gz --no-deps --ignore-installed -vv "
  entry_points:
    - pycoMeth=pycoMeth.__main__:main
  noarch: "python"

requirements:
  build:
    - python>=3.7
    - pip>=19.2.1
    - ripgrep>=11.0.1
  run:
    - numpy>=1.14.0
    - scipy==1.4.1
    - statsmodels>=0.11.1
    - pandas>=1.0.3
    - Jinja2>=2.11.1
    - plotly>=4.7.1
    - pyfaidx>=0.5.8
    - tqdm>=4.45.0
    - colorlog>=4.1.0
    - nbformat>=4.2.0
    - kaleido

test:
  imports:
    - pycoMeth.FileParser
    - pycoMeth.CoordGen
    - pycoMeth.CpG_Aggregate
    - pycoMeth.Interval_Aggregate
    - pycoMeth.Meth_Comp
    - pycoMeth.Comp_Report
    - pycoMeth.CGI_Finder
  commands:
    - pycoMeth CpG_Aggregate --help
    - pycoMeth Interval_Aggregate --help
    - pycoMeth Meth_Comp --help
    - pycoMeth Comp_Report --help
    - pycoMeth CGI_Finder --help

about:
  home: "https://github.com/a-slide/pycoMeth"
  license: "GPL"
  summary: "DNA methylation analysis for Oxford Nanopore DNA sequencing datasets downstream to Nanopolish"
